###post question
POST http://localhost:8082/questions
Content-Type: application/json

{
  "serviceId": 1,
  "content": "¿Cuál es la mejor playa de Colombia?, es que me queda esa pequeña duda",
  "createdBy": {
    "id": "50f60693-b5a9-4f9f-90fc-9c710cdcd1b0",
    "userType": "CUSTOMER",
    "username": "customer1",
    "firstName": "customer1",
    "lastName": "customer1",
    "email": "customer1@mail.com"
  }
}


###post answer to previous question
POST http://localhost:8082/questions/66f4ce240997d43258a9e8bc/answers
Content-Type: application/json

{
  "content": "Me podrías pasar el link? Es que no encuentro tu perfil",
  "createdBy": {
    "id": "50f60693-b5a9-4f9f-90fc-9c710cdcd1b0",
    "userType": "CUSTOMER",
    "username": "customer1",
    "firstName": "customer1",
    "lastName": "customer1",
    "email": "customer1@mail.com"
  }
}